voteswiperProduction:
  component: "@sls-next/serverless-component@3.2.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    bucketRegion: "eu-central-1"
    cloudfront:
      defaults:
        forward:
          headers: [Host]
    domain: ["voteswiper.org"]
    domainType: "both"
    domainRedirects:
      voteswiper.org: https://www.voteswiper.org